import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Modal, Select, TextInput } from '@mantine/core'
import { Pencil, Plus, Shield, UserRoundCheck } from 'lucide-react'
import { notifications } from '@mantine/notifications'
import { apiErrorMessage, createUser, listUsers, updateUserName, updateUserRole } from '../api'
import type { User, UserRole } from '../types'
import { EmptyState, LoadingState, PageHeader, StatusPill } from '../components/common'

const roles = [{ value: 'reviewer', label: '审核员' }, { value: 'standard_reviewer', label: '标准审核员' }, { value: 'viewer', label: '查看者' }, { value: 'admin', label: '管理员' }]
export default function UsersPage() {
  const queryClient = useQueryClient(); const [editing, setEditing] = useState<User | 'new' | null>(null)
  const query = useQuery({ queryKey: ['users'], queryFn: listUsers })
  return <div className="page users-page"><PageHeader eyebrow="ROLE CONTROL" title="用户权限" description="权限之下见职责，结论之上有署名。" actions={<button className="primary-button" onClick={() => setEditing('new')}><Plus size={16}/>新增用户</button>}/>{query.isLoading ? <LoadingState label="正在读取用户权限…"/> : query.isError ? <EmptyState icon="error" title="用户列表读取失败" description="请检查服务状态后重试；失败不会显示为真实空列表。"/> : query.data?.users.length ? <div className="user-table"><div className="user-row head"><span>用户</span><span>员工工号</span><span>角色</span><span>状态</span><span/></div>{query.data.users.map(user => <div className="user-row" key={user.employee_id}><span><i>{(user.name || user.employee_id)[0]}</i><b>{user.name || '未设置姓名'}</b></span><span>{user.employee_id}</span><span><Shield size={14}/>{roles.find(role => role.value === user.role)?.label || user.role}</span><StatusPill status={user.is_active === false ? 'disabled' : 'complete'}>{user.is_active === false ? '已停用' : '可登录'}</StatusPill><button className="icon-button" aria-label={`编辑用户 ${user.name || user.employee_id}`} onClick={() => setEditing(user)}><Pencil size={16}/></button></div>)}</div> : <EmptyState title="还没有用户" description="新增用户并分配角色后，账号才可以进入审核环境。"/>}<Modal opened={Boolean(editing)} onClose={() => setEditing(null)} title={editing === 'new' ? '新增用户' : '编辑用户'} closeButtonProps={{ 'aria-label': '关闭用户编辑窗口' }}><UserForm user={editing === 'new' ? undefined : editing || undefined} onDone={() => { setEditing(null); queryClient.invalidateQueries({ queryKey: ['users'] }) }}/></Modal></div>
}
function UserForm({ user, onDone }: { user?: User; onDone: () => void }) { const [id, setId] = useState(user?.employee_id || ''); const [name, setName] = useState(user?.name || ''); const [role, setRole] = useState<UserRole>(user?.role || 'reviewer'); const [busy, setBusy] = useState(false); async function save() { setBusy(true); try { if (user) { if (name !== user.name) await updateUserName(id, name); if (role !== user.role) await updateUserRole(id, role) } else await createUser(id, role, name); notifications.show({ color: 'green', message: user ? '用户信息已更新' : '用户已创建' }); onDone() } catch (error) { notifications.show({ color: 'red', message: apiErrorMessage(error) }) } finally { setBusy(false) } } return <div className="entity-form"><TextInput label="员工工号" disabled={Boolean(user)} required value={id} onChange={e => setId(e.currentTarget.value)}/><TextInput label="姓名" value={name} onChange={e => setName(e.currentTarget.value)}/><Select label="角色" data={roles} value={role} onChange={value => setRole(value as UserRole)}/><div className="role-note"><UserRoundCheck/><p>修改角色会影响下一次请求的权限，但不会改写历史审核记录。</p></div><div className="modal-actions"><button className="secondary-button" onClick={onDone}>取消</button><button className="primary-button" disabled={!id.trim() || busy} onClick={save}>保存用户</button></div></div> }
